from app.crud.instances import (
    department_crud,
    category_crud,
    emission_factor_crud,
    product_esg_profile_crud,
    environmental_goal_crud,
    esg_policy_crud,
    badge_crud,
    reward_crud,
    carbon_transaction_crud,
    csr_activity_crud,
    employee_participation_crud,
    challenge_crud,
    challenge_participation_crud,
    policy_acknowledgement_crud,
    audit_crud,
    compliance_issue_crud,
    department_score_crud,
)


__all__ = [
    "department_crud",
    "category_crud",
    "emission_factor_crud",
    "product_esg_profile_crud",
    "environmental_goal_crud",
    "esg_policy_crud",
    "badge_crud",
    "reward_crud",
    "carbon_transaction_crud",
    "csr_activity_crud",
    "employee_participation_crud",
    "challenge_crud",
    "challenge_participation_crud",
    "policy_acknowledgement_crud",
    "audit_crud",
    "compliance_issue_crud",
    "department_score_crud",
]